using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace knowledgeBaseUI
{
    public partial class Search : Form
    {
        public Search()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Create a new DataSet
            System.Data.DataSet xmlDataSet = new System.Data.DataSet("XML DataSet");
            // Load the XML document to the DataSet
            xmlDataSet.ReadXml(@"C:\Users\rivaa\source\repos\knowledgeBaseApp\knowledgeBaseLibrary\Data\PostRepository.xml");
            // This line of code is generated by Data Source Configuration Wizard
            PostListControl.DataSource = xmlDataSet.Tables["post"];
        }

        private void AddButton_Click(object sender, EventArgs e)
        {
            var newPost = new NewPost();
            newPost.Show();
        }
    }
}
